services:

  node_arduino_dev:
      build:
         context: ./Server
         dockerfile: docker/Dockerfile

      container_name: node_arduino

      volumes:
        - ./Server:/usr/src/app
      stdin_open: true
      tty: true 

  db:
    image: postgres
    restart: always
    shm_size: 128mb
  
    container_name: circuitnode_db
    
    environment:
      POSTGRES_PASSWORD: circuit123
      POSTGRES_USER: root 
      POSTGRES_DB: circuitnode
    
    volumes:
       - pgdata:/var/lib/postgresql/data

    ports:
       - "5431:5432"
    
volumes:
   pgdata:

