services:

  node_arduino_dev:
      container_name: circuitnode-backend
      build:
         context: ./Server
         dockerfile: ../Dockerfile.backend.dev
      command: npm run dev
      volumes:
        - ./Server:/usr/src/app
      ports: 
        - "3000:3000"
      environment:
        - NODE_ENV=.env
      depends_on:
        - db
      stdin_open: true
      tty: true 

  frontend:
   container_name: circuitnode-frontend
   build:
    context: ./Client
    dockerfile: ../Dockerfile.frontend.dev
   command: npm run dev
   volumes:
   - ./Client:/app
   ports:
   - "5173:5173"
   depends_on:
   - node_arduino_dev

  db:
    image: postgres
    container_name: circuitnode_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: circuit123
      POSTGRES_USER: root 
      POSTGRES_DB: circuitnode
    volumes:
       - pgdata:/var/lib/postgresql/data
    ports:
       - "5431:5432"
    
volumes:
   pgdata:

