FROM node:20-slim AS builder

WORKDIR /app

# necessary instalations for build
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
