FROM node:20-slim

RUN apt-get update && apt-get install -y curl python3 build-essential && rm -rf /var/lib/apt/lists/*


RUN curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
RUN arduino-cli core update-index
RUN arduino-cli core install arduino:avr

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["/usr/src/app/node_modules/.bin/nodemon", "--watch", "src", "--exec", "tsx --tsconfig tsconfig.dev.json src/server.ts"]
